# Generated by Django 5.0.4 on 2024-04-15 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myuser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="is_active",
        ),
    ]
