# Generated by Django 5.0.4 on 2024-04-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myuser", "0002_remove_myuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
