# Generated by Django 5.0.4 on 2024-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myuser", "0003_myuser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=123)),
                ("password", models.CharField(max_length=123)),
                ("code", models.IntegerField()),
            ],
        ),
    ]
