# Generated by Django 5.0.4 on 2024-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comix", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comix",
            name="comix_file",
            field=models.FileField(blank=True, null=True, upload_to="comix/"),
        ),
    ]
