# Generated by Django 5.0.4 on 2024-04-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comix", "0002_alter_comix_comix_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="comix",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comix/images/"),
        ),
    ]
