# Generated by Django 5.0.4 on 2024-04-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comix", "0003_comix_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comix",
            name="chapters",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comix",
            name="pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
