# Generated by Django 5.0.4 on 2024-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comix", "0006_alter_bookmarks_comix_alter_bookmarks_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comix",
            name="watches",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comments",
            name="text",
            field=models.TextField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Watched",
        ),
    ]
