# Generated by Django 5.0.4 on 2024-04-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comix", "0008_alter_comix_watches"),
    ]

    operations = [
        migrations.AddField(
            model_name="comix",
            name="common_grade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-03-12 13:11:23"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comments",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
