# Generated by Django 5.0.4 on 2024-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comix", "0009_comix_common_grade_comments_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (10, 10),
                    (9, 9),
                    (8, 8),
                    (7, 7),
                    (6, 6),
                    (5, 5),
                    (4, 4),
                    (3, 3),
                    (2, 2),
                    (1, 1),
                ]
            ),
        ),
    ]
