# Generated by Django 5.0.4 on 2024-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comix", "0010_alter_rating_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="comix/images"),
                ),
            ],
        ),
    ]
