# Generated by Django 5.0.4 on 2024-05-13 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comix", "0012_genre_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comix",
            name="comix_pages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
